[project]
name = "fasthtml-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "monsterui>=1.0.20",
    "pandas>=2.2.3",
    "python-fasthtml>=0.12.18",
]
